### ISSUE TITLE
Add proxy

### ISSUE THREAD

**Issue by mhkanon** [chris1111/Download-BigSur#4]
Can it possible to add proxy this apps(like socks4)? I always use a proxy for download. Because the normal line is slower than the proxy. If possible add the system set proxy socks4. Thank you.

**Comment by chris1111** [comment]
You can test your self to modifying the script
See in bundle Contents/resources/**Download** open the file with textedit or any other text editor
This line⬇︎
curl -L --progress-bar http://swcdn.apple.com/content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/InstallAssistant.pkg -o /Private/tmp/InstallAssistant.pkg

**Comment by mhkanon** [comment]
Thank you. The link is working. After installed the *.pkg Show the "Big sure" icon in the "Application" menu?
